### ISSUE TITLE
Scaffolding checklist

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#1]
These tasks can / should get split out to individual PRs. If you're working on something, edit this post and put your name next to it. 

## Continuous Integration
- [x] Rubocop
  - [x] rubocop-rspec
  - [x] rubocop-performance
  - [x] rubocop-rails
- [x] Testing suite
  - [x] RSpec
  - [x] Capybara
  - [x] Webdrivers
  - [x] Webmock
- [x] continuous integration
  - [x] TravisCI 
  - [x] ~Code climate~ (#3)
  - [x] SCSS lint

## Deployment
- [x] Shared configs
- [x] add railsconfig
- [x] Monitoring
  - [x] OKcomputer
  - [x] ~Honeybadger~ (#4)
  - [x] New Relic
  - [x] Nagios
- [x] DLSS capistrano --> dev and UAT (WIP; need mysql2 gem installed)
- [x] ~Google analytics~ (#2)
  - [x] ~IP address truncation~
- [x] add the project to the update script

## Other
- [x] README - Josh: taking a first pass at basic readme
