### ISSUE TITLE
Add checkout status-specific detail information

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#120]
# Grouped by status

## Checked out
- Renewal status
- Borrowed on
- Last Renewed on
- Loan period
- Remaining
- Source

Actions:
- Renew (if eligible)
- View in Searchworks

## Recalled
- Renewal Status
- Borrowed on
- Recalled on
- Source

Actions:
- View in Searchworks

## Overdue
- Renewal status
- Borrowed on
- Fines accruing (if overdue, accruing fines)
- Days overdue
- Source

Actions:
- Renew (if eligible)
- View in Searchworks

## Overdue, billed, assumed lost
- Renewal status
- Borrowed on
- Days overdue
- Assumed lost on
- Assumed lost fee
- Source

Actions:
- Pay $total now --> needs to be reviewed in #188 and #186
- View in Searchworks

# Combined view
- [x] Renewal status
- [x]  Borrowed on
- [x]  Last Renewed on (if renewable)
- [x]  Loan period (if renewable) #142 (logic), UI split out to #204)
- [x]  Remaining (if checkout, not recalled or overdue) #125 
- [x]  Recalled on (if recalled)
- [x]  Days overdue (if overdue) Split out to #185
- [x]  Fines accruing (if overdue, accruing fines (but not assumed lost))  #163
- [ ]  Assumed lost on (if assumed lost) #186 
- [x]  Assumed lost fee (if assumed lost)
- [x] Claimed returned (if claimed returned)
- [x]  Source

Actions:
- [x]  Renew (if eligible and not recalled or assumed lost)
- [x]  View in Searchworks

# TODO
- [ ] display something else in Source if it's from BorrowDirect

**Comment by camillevilla** [comment]
I'm not clear that we need `Days overdue`. It's outlined in the content labels doc but doesn't show up in the mockups. @tallenaz and I worked on some logic that calculates `days_overdue`, but are we actually using this? Symphony returns the `estimatedOverdueAmount` as a dollar amount.

**Comment by cbeer** [comment]
@jvine : ^

**Comment by jvine** [comment]
**Content doc trumps the mockups.** (I created the doc because it was impossible to keep everything accurate and consistent in the mockups.) The doc has had a lot of review & negotiation with @seestone, but is nonetheless open to discussion as we discover what's possible/extra difficult. If this value is problematic, it's fine to set it aside for now. (Also just realized for reserve items we might need hours overdue...)

**Comment by camillevilla** [comment]
👍@jvine I think adding the logic for days overdue is fine.  The feature might look a little wonky until we have the logic for distinguishing hourly loans from regular checkouts, but we'll get there soon.

Let's plan on spending some time going over the content doc at tomorrow's planning meeting so that devs are well acquainted with it. Right now folks are mostly consulting the mock ups when looking for clarification.

**Comment by mejackreed** [comment]
Based off of comments in the Content doc, I'm not sure that we have access to / or the ability to get additional information to support the `assumed lost on` or `assumed lost fee` information? Should we strike those through?

**Comment by cbeer** [comment]
Maybe we could do some weird join between blocks + checkouts to figure out if a checked out item has an associated fee? That might get pretty hairy.

**Comment by jvine** [comment]
The same item will be displayed on the Fines tab at this point, because it's been billed, and the amount will be shown there. Can we not access that info from Checkouts?

(It continues to appear on Checkouts as well, because you do have it out and if you return it you'll get some credit.)

**Comment by shelleydoljack** [comment]
This might answer Chris's question:
>Maybe we could do some weird join between blocks + checkouts to figure out if a checked out item has an associated fee? That might get pretty hairy.
There is an itemCircInfo resource that has a field totalBills. This might help one figure out if an item has a current bill, but I'm not sure:
```
https://${host}/${webapp}/circulation/itemCircInfo/key/12735651:1:1
{
    "resource": "/circulation/itemCircInfo",
    "key": "12735651:1:1",
    "fields": {
        "circSetID": null,
        "circStatus": "CHECKED_OUT",
        "currentBookings": 0,
        "currentCheckOuts": 1,
        "goingTogether": false,
        "inHouseUses": 0,
        "intervalCheckOuts": 1,
        "intervalDate": null,
        "intervalRenewals": 0,
        "inventoriedCount": 0,
        "inventoriedDate": null,
        "lastActivityDate": "2019-07-08",
        "lastCheckInDate": null,
        "lastCheckOutDate": "2019-07-08",
        "reserveCollection": null,
        "totalBills": 0,
        "totalCheckOuts": 1,
        "totalRenewals": 0,
        "totalCheckOutsAndRenewals": 1,
        "lastPatron": null
    }
}
```

**Comment by camillevilla** [comment]
I've split out #186 (`assumed lost` fees) and #204 (`loan period`).
