### ISSUE TITLE
Add Checkouts tab displaying checked out material

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#18]
- [x] retrieve checkouts for a user using the Symphony API (Prerequisite: #13 )
- [x] translate internal codes (like library/location) to better user facing labels 
- [x] display them (Prerequisite: #16 (figuring out our generic data tables approach)) on the page
- [x] add a collapsable section with more information
- [x] provide a link to the item in Searchworks (#77 )
- [x] set an appropriate background color depending on the items status
- [x] pull recalled items to the top of the page
- [ ] make the data sortable using the sort widget (and, optionally, using the column headers)

## Mobile
<img width="378" alt="Screen Shot 2019-07-08 at 15 48 01" src="https://user-images.githubusercontent.com/111218/60847538-c80dec00-a197-11e9-9312-0a9168cb46a3.png">

## Desktop
<img width="895" alt="Screen Shot 2019-07-08 at 15 47 50" src="https://user-images.githubusercontent.com/111218/60847528-c0e6de00-a197-11e9-83b7-1b1f34689f7b.png">

**Comment by mejackreed** [comment]
In starting to look at this issue, I created a spike in #46 on how this all might hook up together.

**Comment by jkeck** [comment]
I'm going to pickup `pull recalled items to the top of the page`

**Comment by cbeer** [comment]
@jkeck I've went ahead and grabbed that & background colors.
