### ISSUE TITLE
Hook up checkouts display + functionality

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#825]
This ticket builds on the initial FOLIO mappings + https://github.com/sul-dlss/mylibrary/pull/824. These are the known TODOs:

- [x] `renewable_at` / `renew_from_period` (related to https://github.com/sul-dlss/folio-graphql/issues/34?)
  > folio loan policies have a string field called `renewalsPolicy.renewFromId` described as the "Renew from date". we currently only have one loan policy that has this field defined, and it's set to the string `SYSTEM_DATE`. i don't really know what this means...maybe it's a reference to another field on the loan object itself?
  > for items where renewals have the same length as regular checkouts, this information is an object stored at `loansPolicy.period` on the loan policy:
   ```js
        "loansPolicy": {
         "period": { "duration": 28, "intervalId": "Days" },
        }
     ```
  > 
  > some loan policies can also specify an alternate time length for renewals, which supersedes the length of a regular checkout. if present, that information is in `renewalsPolicy`:
  > 
  ```js
    "renewalsPolicy": {
     "differentPeriod": true,
     "period": { "duration": 5, "intervalId": "Days" },
    }
  ```
  > we don't currently have any policies with a different length for renewals.
  
- [x] `reserve_item?`
  > there's currently no information in a loan policy that identifies it as being specifically for a reserve item (although we do usually put something in the description field about it).
- [x] seen + unseen renewals remaining (FOLIO doesn't make this distinction, so presumably we'll set seen renewals to 0 and use the policies count for unseen renewals)

   > the total number of allowed renewals is renewalsPolicy.numberAllowed on the loan policy.     the number of renewals the patron has used up for that particular item is renewalCount on the checkout object.

- [x] `library`
- [ ] `from_ill?` / `from_ilb?` / `from_borrow_direct?` (https://github.com/sul-dlss/mylibrary/issues/833)
- [x] `renewal_date` / `recalled_date` (https://github.com/sul-dlss/folio-graphql/issues/35)
   > recalls and renewals can use the [/loan-storage/loan-history](https://s3.amazonaws.com/foliodocs/api/mod-circulation-storage/r/loan-storage.html#loan_storage_loan_history_get) API with a CQL query filtering on both the loan ID and the action type.

Actions:
- [x]  confirm we can renew eligible material.

**Comment by cbeer** [comment]
In the abstract, gathering information using the loan-history API seems complicated. Maybe it won't be so bad once we dig into it... or if it's as bad as it sounds, maybe we revisit the design to omit that for the FOLIO launch.

**Comment by saseestone** [comment]
Are we handling recalls in this ticket (aside from if the item can be renewed?) We should be displaying to the user if the item has been recalled.

**Comment by cbeer** [comment]
We found `dueDateChangedByRecall` as the indicator something's been recalled, and I believe we've already hooked that up. I think we're still missing the date when the recall was made (from the details page), but haven't found a good way to get that information (short of pulling the whole loan history)

**Comment by saseestone** [comment]
In case it's needed, I just placed a Recall request on 36105227362600 (checked out to grad1, requested by undergrad1)

**Comment by corylown** [comment]
I created https://github.com/sul-dlss/mylibrary/issues/862 to cover the remaining ILL-related pieces that are blocked until we get ILL examples that are not from BorrowDirect. I think the rest of this is completed.
