### ISSUE TITLE
Add Fines and fees tab for displaying fines

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#86]
✅ #18 is probably a prerequisite that'll lay down some UI patterns.
✅ #88 is also a prerequisite to pull data out of Symphony.

## TODO
- [x] Figure out set of data for display (and ensure it is returned from the API)
- [ ] Translate statuses returned from API for display (split out to #155) 
- [~] ~Build out `accruing` section~ (#140 split out)
- [~] ~Add a sortable `history` section~ (#137 split out)

<img width="381" alt="Screen Shot 2019-07-11 at 19 42 36" src="https://user-images.githubusercontent.com/111218/61098507-16c7ba00-a414-11e9-8f86-3fbf22d5d882.png">

**Comment by jkeck** [comment]
@saseestone / @jvine do we have a mapping of what the statuses we get from Symphony should display to users (e.g. `Overdue recall` / `Assumed Lost`)

**Comment by cbeer** [comment]
I believe these are all the possible types that would need translating (although some of them are probably not applicable?)

- [ ] "SHIPPING_COST",
- [ ]  "RESERVE_ITEM_OVERDUE",
- [ ]  "LOST_ITEM",
- [ ]  "RECALLED_ITEM_OVERDUE",
- [ ]  "ITEM_OVERDUE",
- [ ]  "HOLDASSIST_FEE",
- [ ]  "NO_SPECIAL",
- [ ]  "CHARGE_FEE",
- [ ]  "HOLDSELF_FEE",
- [ ]  "PROCESSING_FEE",
- [ ]  "HOLD_FEE",
- [ ]  "PRIVILEGE_FEE"

**Comment by saseestone** [comment]
So the list that Chris added above must be the webservices labels for the "Bill Reasons" that I see in the policies list in WorkFlows.  (slightly different wording...so we'd want @shelleydoljack to confirm that we're not using a WorkFlows policy...differently...than web services is expecting.  (e.g. our odd use of "group ID" in policies vs. the auth id field in a user record.)

We use the following "Bill Reasons":
Symphony policy "Bill Reason" name -> Web services label (?) -> Sarah's recommended translation
OVERDUE -> ITEM_OVERDUE -> Overdue item
RECALLOVD -> RECALLED_ITEM_OVERDUE -> Overdue recall
RESERVEOVD -> RESERVE_ITEM_OVERDUE -> Overdue course reserve
LOST -> LOST_ITEM -> Lost item
REPLCMENT -> ? -> Lost item
LOST-ILL -> ? -> Lost interlibrary loan item
CLAIM-LOST -> ? -> Lost item
CLAIM-FEE -> ? -> Lost item billing fee
PROCESSFEE -> PROCESSING_FEE -> Lost item billing fee
PROCESSING -> ? -> Lost item billing fee
DAMAGED -> ? -> Damaged item
PRIVILEGES -> PRIVILEGE_FEE -> Privileges fee
LOSTCARD -> ? -> Lost card fee
LOSTKEY -> ? -> Lost key fee

Older bills that we have in the database and *could* should up in My Account:
BILLED-OD -> ? -> Lost item
BILLING-FEE -> ? -> Lost item billing fee
PRE-NOTIS -> ? -> Lost item
PRE-UNICRN -> ? -> Lost item
RECAL-BILL -> ? -> Lost item
RECAL-FEE -> ? -> Overdue recall
RECOD-MBIL -> ? -> Lost item
RECOD-MFEE -> ? -> Lost item billing fee
RECOD-MOD -> ? -> Lost item

Delivered policies that exist in Symphony but we don't use at Stanford...but *could* should up sometime/somewhere:
BADCHECK -> ? -> Privileges fee
LOSTRECALL -> ? -> Lost item
MISC -> ? -> Overdue item

**Comment by camillevilla** [comment]
Thanks for the check @jvine and @saseestone. I've split this info out to #155 for @shelleydoljack and someone else to pair on.
